var newele=document.createElement('div');
var il=document.querySelector('header .container');
var firstElem=document.querySelector('header h1');
var texte=document.createTextNode('HEllo');
newele.appendChild(texte);
//firstElem.parentElement.insertBefore(newele,firstElem);
il.insertBefore(newele,firstElem);
var newele1=document.createElement('div');
newele1.setAttribute('id','text1');
newele1.className="elements";
var texte1=document.createTextNode('HEllo');
newele1.appendChild(texte1);
var lis=document.querySelector('.container ul');
var befli=document.querySelector('ul li');
befli.parentElement.insertBefore(newele1,befli);